// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/agent/proto/sandbox.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateNewPaymentReferenceInput struct {
	CurrencyCode         string   `protobuf:"bytes,1,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	Ref1                 string   `protobuf:"bytes,3,opt,name=Ref1,proto3" json:"Ref1,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	ExpireAt             int64    `protobuf:"varint,4,opt,name=ExpireAt,proto3" json:"ExpireAt,omitempty"`
	PaymentID            string   `protobuf:"bytes,5,opt,name=PaymentID,proto3" json:"PaymentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewPaymentReferenceInput) Reset()         { *m = CreateNewPaymentReferenceInput{} }
func (m *CreateNewPaymentReferenceInput) String() string { return proto.CompactTextString(m) }
func (*CreateNewPaymentReferenceInput) ProtoMessage()    {}
func (*CreateNewPaymentReferenceInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_c52a1a689a3694bc, []int{0}
}

func (m *CreateNewPaymentReferenceInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewPaymentReferenceInput.Unmarshal(m, b)
}
func (m *CreateNewPaymentReferenceInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewPaymentReferenceInput.Marshal(b, m, deterministic)
}
func (m *CreateNewPaymentReferenceInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewPaymentReferenceInput.Merge(m, src)
}
func (m *CreateNewPaymentReferenceInput) XXX_Size() int {
	return xxx_messageInfo_CreateNewPaymentReferenceInput.Size(m)
}
func (m *CreateNewPaymentReferenceInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewPaymentReferenceInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewPaymentReferenceInput proto.InternalMessageInfo

func (m *CreateNewPaymentReferenceInput) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *CreateNewPaymentReferenceInput) GetRef1() string {
	if m != nil {
		return m.Ref1
	}
	return ""
}

func (m *CreateNewPaymentReferenceInput) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateNewPaymentReferenceInput) GetExpireAt() int64 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

func (m *CreateNewPaymentReferenceInput) GetPaymentID() string {
	if m != nil {
		return m.PaymentID
	}
	return ""
}

type CreateNewPaymentReferenceOutput struct {
	Result               *CreateNewPaymentReferenceOutput_Output `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string                                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *CreateNewPaymentReferenceOutput) Reset()         { *m = CreateNewPaymentReferenceOutput{} }
func (m *CreateNewPaymentReferenceOutput) String() string { return proto.CompactTextString(m) }
func (*CreateNewPaymentReferenceOutput) ProtoMessage()    {}
func (*CreateNewPaymentReferenceOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_c52a1a689a3694bc, []int{1}
}

func (m *CreateNewPaymentReferenceOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewPaymentReferenceOutput.Unmarshal(m, b)
}
func (m *CreateNewPaymentReferenceOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewPaymentReferenceOutput.Marshal(b, m, deterministic)
}
func (m *CreateNewPaymentReferenceOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewPaymentReferenceOutput.Merge(m, src)
}
func (m *CreateNewPaymentReferenceOutput) XXX_Size() int {
	return xxx_messageInfo_CreateNewPaymentReferenceOutput.Size(m)
}
func (m *CreateNewPaymentReferenceOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewPaymentReferenceOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewPaymentReferenceOutput proto.InternalMessageInfo

func (m *CreateNewPaymentReferenceOutput) GetResult() *CreateNewPaymentReferenceOutput_Output {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateNewPaymentReferenceOutput) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateNewPaymentReferenceOutput_Output struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Format               string   `protobuf:"bytes,3,opt,name=Format,proto3" json:"Format,omitempty"`
	PaymentURI           string   `protobuf:"bytes,4,opt,name=PaymentURI,proto3" json:"PaymentURI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewPaymentReferenceOutput_Output) Reset() {
	*m = CreateNewPaymentReferenceOutput_Output{}
}
func (m *CreateNewPaymentReferenceOutput_Output) String() string { return proto.CompactTextString(m) }
func (*CreateNewPaymentReferenceOutput_Output) ProtoMessage()    {}
func (*CreateNewPaymentReferenceOutput_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_c52a1a689a3694bc, []int{1, 0}
}

func (m *CreateNewPaymentReferenceOutput_Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewPaymentReferenceOutput_Output.Unmarshal(m, b)
}
func (m *CreateNewPaymentReferenceOutput_Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewPaymentReferenceOutput_Output.Marshal(b, m, deterministic)
}
func (m *CreateNewPaymentReferenceOutput_Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewPaymentReferenceOutput_Output.Merge(m, src)
}
func (m *CreateNewPaymentReferenceOutput_Output) XXX_Size() int {
	return xxx_messageInfo_CreateNewPaymentReferenceOutput_Output.Size(m)
}
func (m *CreateNewPaymentReferenceOutput_Output) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewPaymentReferenceOutput_Output.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewPaymentReferenceOutput_Output proto.InternalMessageInfo

func (m *CreateNewPaymentReferenceOutput_Output) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateNewPaymentReferenceOutput_Output) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateNewPaymentReferenceOutput_Output) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *CreateNewPaymentReferenceOutput_Output) GetPaymentURI() string {
	if m != nil {
		return m.PaymentURI
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateNewPaymentReferenceInput)(nil), "agent.CreateNewPaymentReferenceInput")
	proto.RegisterType((*CreateNewPaymentReferenceOutput)(nil), "agent.CreateNewPaymentReferenceOutput")
	proto.RegisterType((*CreateNewPaymentReferenceOutput_Output)(nil), "agent.CreateNewPaymentReferenceOutput.Output")
}

func init() { proto.RegisterFile("pkg/agent/proto/sandbox.proto", fileDescriptor_c52a1a689a3694bc) }

var fileDescriptor_c52a1a689a3694bc = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdb, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0x53, 0x0e, 0xcd, 0xbf, 0xf3, 0xe7, 0x6a, 0x62, 0xb4, 0x10, 0x45, 0x42, 0xa2, 0xe1,
	0xc6, 0x36, 0xe2, 0x13, 0x20, 0x62, 0xc2, 0x8d, 0x9a, 0x55, 0x6f, 0xbc, 0x2b, 0x32, 0xe0, 0x89,
	0xdd, 0x66, 0x99, 0x46, 0xf0, 0x91, 0x7c, 0x32, 0x1f, 0xc3, 0x74, 0xba, 0x1e, 0x13, 0x82, 0x57,
	0x3b, 0xdf, 0xb7, 0x99, 0xf6, 0x37, 0xdf, 0x2c, 0xec, 0xa4, 0x8f, 0xd3, 0x38, 0x99, 0x92, 0xe6,
	0x38, 0xb5, 0x86, 0x4d, 0x3c, 0x4f, 0xf4, 0x78, 0x64, 0x16, 0x91, 0x28, 0xac, 0xca, 0x55, 0xfb,
	0xd5, 0x83, 0x66, 0xdf, 0x52, 0xc2, 0x74, 0x46, 0xcf, 0x17, 0xc9, 0x72, 0x46, 0x9a, 0x15, 0x4d,
	0xc8, 0x92, 0xbe, 0xa5, 0xa1, 0x4e, 0x33, 0xc6, 0x36, 0xd4, 0xfa, 0x99, 0xcd, 0x8d, 0x65, 0xdf,
	0x8c, 0x29, 0xf4, 0x5a, 0x5e, 0x27, 0x50, 0x3f, 0x3c, 0x44, 0xa8, 0x28, 0x9a, 0x1c, 0x86, 0x65,
	0xb9, 0x93, 0x1a, 0x37, 0xc1, 0xef, 0xcd, 0x4c, 0xa6, 0x39, 0x2c, 0xb5, 0xbc, 0x4e, 0x49, 0x39,
	0x85, 0x0d, 0xf8, 0x37, 0x58, 0xa4, 0xf7, 0x96, 0x7a, 0x1c, 0x56, 0x5a, 0x5e, 0xa7, 0xac, 0x3e,
	0x35, 0x6e, 0x43, 0xe0, 0x20, 0x86, 0x27, 0x61, 0x55, 0x3e, 0xf6, 0x65, 0xb4, 0xdf, 0x3c, 0xd8,
	0x5d, 0x09, 0x7b, 0x9e, 0x71, 0x4e, 0x3b, 0x00, 0xdf, 0xd2, 0x3c, 0x7b, 0x62, 0xe1, 0xfc, 0xdf,
	0x3d, 0x88, 0x64, 0xd0, 0x68, 0x4d, 0x5f, 0x54, 0x1c, 0xca, 0x35, 0xe3, 0x06, 0x54, 0xc9, 0x5a,
	0x63, 0x85, 0x3d, 0x50, 0x85, 0x68, 0xdc, 0x81, 0xef, 0x7e, 0x83, 0x50, 0xb9, 0x5a, 0xa6, 0x1f,
	0x61, 0x48, 0x9d, 0x7b, 0x12, 0x50, 0xd1, 0x22, 0x75, 0x1e, 0xc2, 0xa9, 0xb1, 0xb3, 0x84, 0x5d,
	0x34, 0x4e, 0x61, 0x13, 0xc0, 0x81, 0x5c, 0xab, 0xa1, 0xc4, 0x10, 0xa8, 0x6f, 0x4e, 0xf7, 0x05,
	0x6a, 0x97, 0xc5, 0xbe, 0x7a, 0x39, 0x3e, 0x3e, 0x40, 0x7d, 0xe5, 0x04, 0xb8, 0xb7, 0x6e, 0x46,
	0x59, 0x64, 0x63, 0xff, 0x6f, 0x51, 0x1c, 0xd7, 0x6f, 0xb6, 0xe6, 0x66, 0xc2, 0x9a, 0x38, 0xfe,
	0xf5, 0x86, 0x46, 0xbe, 0x1c, 0x47, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x6a, 0x1f, 0x58,
	0x5d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SandboxAgentClient is the client API for SandboxAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SandboxAgentClient interface {
	CreateNewPaymentReference(ctx context.Context, in *CreateNewPaymentReferenceInput, opts ...grpc.CallOption) (*CreateNewPaymentReferenceOutput, error)
}

type sandboxAgentClient struct {
	cc *grpc.ClientConn
}

func NewSandboxAgentClient(cc *grpc.ClientConn) SandboxAgentClient {
	return &sandboxAgentClient{cc}
}

func (c *sandboxAgentClient) CreateNewPaymentReference(ctx context.Context, in *CreateNewPaymentReferenceInput, opts ...grpc.CallOption) (*CreateNewPaymentReferenceOutput, error) {
	out := new(CreateNewPaymentReferenceOutput)
	err := c.cc.Invoke(ctx, "/agent.SandboxAgent/CreateNewPaymentReference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxAgentServer is the server API for SandboxAgent service.
type SandboxAgentServer interface {
	CreateNewPaymentReference(context.Context, *CreateNewPaymentReferenceInput) (*CreateNewPaymentReferenceOutput, error)
}

func RegisterSandboxAgentServer(s *grpc.Server, srv SandboxAgentServer) {
	s.RegisterService(&_SandboxAgent_serviceDesc, srv)
}

func _SandboxAgent_CreateNewPaymentReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewPaymentReferenceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).CreateNewPaymentReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.SandboxAgent/CreateNewPaymentReference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).CreateNewPaymentReference(ctx, req.(*CreateNewPaymentReferenceInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _SandboxAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.SandboxAgent",
	HandlerType: (*SandboxAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewPaymentReference",
			Handler:    _SandboxAgent_CreateNewPaymentReference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/proto/sandbox.proto",
}
