// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/proto/payment.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfirmPaymentCashInInput struct {
	PaymentID            string   `protobuf:"bytes,1,opt,name=PaymentID,proto3" json:"PaymentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPaymentCashInInput) Reset()         { *m = ConfirmPaymentCashInInput{} }
func (m *ConfirmPaymentCashInInput) String() string { return proto.CompactTextString(m) }
func (*ConfirmPaymentCashInInput) ProtoMessage()    {}
func (*ConfirmPaymentCashInInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_428c3b718c6302e1, []int{0}
}

func (m *ConfirmPaymentCashInInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPaymentCashInInput.Unmarshal(m, b)
}
func (m *ConfirmPaymentCashInInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPaymentCashInInput.Marshal(b, m, deterministic)
}
func (m *ConfirmPaymentCashInInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPaymentCashInInput.Merge(m, src)
}
func (m *ConfirmPaymentCashInInput) XXX_Size() int {
	return xxx_messageInfo_ConfirmPaymentCashInInput.Size(m)
}
func (m *ConfirmPaymentCashInInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPaymentCashInInput.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPaymentCashInInput proto.InternalMessageInfo

func (m *ConfirmPaymentCashInInput) GetPaymentID() string {
	if m != nil {
		return m.PaymentID
	}
	return ""
}

type ConfirmPaymentCashInOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPaymentCashInOutput) Reset()         { *m = ConfirmPaymentCashInOutput{} }
func (m *ConfirmPaymentCashInOutput) String() string { return proto.CompactTextString(m) }
func (*ConfirmPaymentCashInOutput) ProtoMessage()    {}
func (*ConfirmPaymentCashInOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_428c3b718c6302e1, []int{1}
}

func (m *ConfirmPaymentCashInOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPaymentCashInOutput.Unmarshal(m, b)
}
func (m *ConfirmPaymentCashInOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPaymentCashInOutput.Marshal(b, m, deterministic)
}
func (m *ConfirmPaymentCashInOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPaymentCashInOutput.Merge(m, src)
}
func (m *ConfirmPaymentCashInOutput) XXX_Size() int {
	return xxx_messageInfo_ConfirmPaymentCashInOutput.Size(m)
}
func (m *ConfirmPaymentCashInOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPaymentCashInOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPaymentCashInOutput proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ConfirmPaymentCashInInput)(nil), "agent.ConfirmPaymentCashInInput")
	proto.RegisterType((*ConfirmPaymentCashInOutput)(nil), "agent.ConfirmPaymentCashInOutput")
}

func init() { proto.RegisterFile("pkg/api/proto/payment.proto", fileDescriptor_428c3b718c6302e1) }

var fileDescriptor_428c3b718c6302e1 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0xc8, 0x4e, 0xd7,
	0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x48, 0xac, 0xcc, 0x4d, 0xcd,
	0x2b, 0xd1, 0x03, 0xf3, 0x84, 0x58, 0x13, 0xd3, 0x53, 0xf3, 0x4a, 0x94, 0x2c, 0xb9, 0x24, 0x9d,
	0xf3, 0xf3, 0xd2, 0x32, 0x8b, 0x72, 0x03, 0x20, 0xd2, 0xce, 0x89, 0xc5, 0x19, 0x9e, 0x79, 0x9e,
	0x79, 0x05, 0xa5, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0x50, 0x51, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x84, 0x80, 0x92, 0x0c, 0x97, 0x14, 0x36, 0xad, 0xfe, 0xa5, 0x25, 0x05, 0xa5,
	0x25, 0x46, 0x69, 0x5c, 0xec, 0x50, 0x61, 0xa1, 0x68, 0x2e, 0x11, 0x6c, 0x0a, 0x85, 0x14, 0xf4,
	0xc0, 0x6e, 0xd0, 0xc3, 0xe9, 0x00, 0x29, 0x45, 0x3c, 0x2a, 0x20, 0xf6, 0x38, 0x89, 0x47, 0x89,
	0x16, 0xe7, 0xa7, 0x95, 0xe4, 0xa5, 0x96, 0xe8, 0xa3, 0x78, 0x37, 0x89, 0x0d, 0x4c, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xb6, 0xd3, 0x9a, 0x06, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentClient interface {
	ConfirmPaymentCashIn(ctx context.Context, in *ConfirmPaymentCashInInput, opts ...grpc.CallOption) (*ConfirmPaymentCashInOutput, error)
}

type paymentClient struct {
	cc *grpc.ClientConn
}

func NewPaymentClient(cc *grpc.ClientConn) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) ConfirmPaymentCashIn(ctx context.Context, in *ConfirmPaymentCashInInput, opts ...grpc.CallOption) (*ConfirmPaymentCashInOutput, error) {
	out := new(ConfirmPaymentCashInOutput)
	err := c.cc.Invoke(ctx, "/agent.Payment/ConfirmPaymentCashIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
type PaymentServer interface {
	ConfirmPaymentCashIn(context.Context, *ConfirmPaymentCashInInput) (*ConfirmPaymentCashInOutput, error)
}

func RegisterPaymentServer(s *grpc.Server, srv PaymentServer) {
	s.RegisterService(&_Payment_serviceDesc, srv)
}

func _Payment_ConfirmPaymentCashIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentCashInInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ConfirmPaymentCashIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Payment/ConfirmPaymentCashIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ConfirmPaymentCashIn(ctx, req.(*ConfirmPaymentCashInInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Payment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmPaymentCashIn",
			Handler:    _Payment_ConfirmPaymentCashIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/payment.proto",
}
