// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/proto/payment.proto

package proto // import "softnet/pkg/api/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PaymentStatus int32

const (
	PaymentStatus_INITIAL                  PaymentStatus = 0
	PaymentStatus_READY_TO_CASH_IN         PaymentStatus = 1
	PaymentStatus_CASH_IN_CONFIRM          PaymentStatus = 2
	PaymentStatus_CALLBACK_ATTEMPT_SUCCESS PaymentStatus = 3
	PaymentStatus_CALLBACK_ATTEMPT_FAILED  PaymentStatus = 4
	PaymentStatus_FAILED                   PaymentStatus = 5
)

var PaymentStatus_name = map[int32]string{
	0: "INITIAL",
	1: "READY_TO_CASH_IN",
	2: "CASH_IN_CONFIRM",
	3: "CALLBACK_ATTEMPT_SUCCESS",
	4: "CALLBACK_ATTEMPT_FAILED",
	5: "FAILED",
}
var PaymentStatus_value = map[string]int32{
	"INITIAL":                  0,
	"READY_TO_CASH_IN":         1,
	"CASH_IN_CONFIRM":          2,
	"CALLBACK_ATTEMPT_SUCCESS": 3,
	"CALLBACK_ATTEMPT_FAILED":  4,
	"FAILED":                   5,
}

func (x PaymentStatus) String() string {
	return proto.EnumName(PaymentStatus_name, int32(x))
}
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{0}
}

type PaymentAgent struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentAgent) Reset()         { *m = PaymentAgent{} }
func (m *PaymentAgent) String() string { return proto.CompactTextString(m) }
func (*PaymentAgent) ProtoMessage()    {}
func (*PaymentAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{0}
}
func (m *PaymentAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentAgent.Unmarshal(m, b)
}
func (m *PaymentAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentAgent.Marshal(b, m, deterministic)
}
func (dst *PaymentAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentAgent.Merge(dst, src)
}
func (m *PaymentAgent) XXX_Size() int {
	return xxx_messageInfo_PaymentAgent.Size(m)
}
func (m *PaymentAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentAgent.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentAgent proto.InternalMessageInfo

func (m *PaymentAgent) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PaymentAgent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type History struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Memo                 string   `protobuf:"bytes,2,opt,name=Memo,proto3" json:"Memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{1}
}
func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (dst *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(dst, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *History) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type Transaction struct {
	ID                   string        `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PaymentProvider      *PaymentAgent `protobuf:"bytes,2,opt,name=PaymentProvider,proto3" json:"PaymentProvider,omitempty"`
	CashInReference      string        `protobuf:"bytes,3,opt,name=CashInReference,proto3" json:"CashInReference,omitempty"`
	Currency             string        `protobuf:"bytes,4,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Amount               float32       `protobuf:"fixed32,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	History              []*History    `protobuf:"bytes,6,rep,name=History,proto3" json:"History,omitempty"`
	CashInType           string        `protobuf:"bytes,7,opt,name=CashInType,proto3" json:"CashInType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{2}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Transaction) GetPaymentProvider() *PaymentAgent {
	if m != nil {
		return m.PaymentProvider
	}
	return nil
}

func (m *Transaction) GetCashInReference() string {
	if m != nil {
		return m.CashInReference
	}
	return ""
}

func (m *Transaction) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Transaction) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetHistory() []*History {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *Transaction) GetCashInType() string {
	if m != nil {
		return m.CashInType
	}
	return ""
}

type UpdatePaymentStatusInput struct {
	ID                   string        `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               PaymentStatus `protobuf:"varint,2,opt,name=Status,proto3,enum=agent.PaymentStatus" json:"Status,omitempty"`
	Memo                 string        `protobuf:"bytes,3,opt,name=Memo,proto3" json:"Memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdatePaymentStatusInput) Reset()         { *m = UpdatePaymentStatusInput{} }
func (m *UpdatePaymentStatusInput) String() string { return proto.CompactTextString(m) }
func (*UpdatePaymentStatusInput) ProtoMessage()    {}
func (*UpdatePaymentStatusInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{3}
}
func (m *UpdatePaymentStatusInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePaymentStatusInput.Unmarshal(m, b)
}
func (m *UpdatePaymentStatusInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePaymentStatusInput.Marshal(b, m, deterministic)
}
func (dst *UpdatePaymentStatusInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePaymentStatusInput.Merge(dst, src)
}
func (m *UpdatePaymentStatusInput) XXX_Size() int {
	return xxx_messageInfo_UpdatePaymentStatusInput.Size(m)
}
func (m *UpdatePaymentStatusInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePaymentStatusInput.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePaymentStatusInput proto.InternalMessageInfo

func (m *UpdatePaymentStatusInput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdatePaymentStatusInput) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return PaymentStatus_INITIAL
}

func (m *UpdatePaymentStatusInput) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type UpdatePaymentStatusOutput struct {
	Result               *Transaction `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdatePaymentStatusOutput) Reset()         { *m = UpdatePaymentStatusOutput{} }
func (m *UpdatePaymentStatusOutput) String() string { return proto.CompactTextString(m) }
func (*UpdatePaymentStatusOutput) ProtoMessage()    {}
func (*UpdatePaymentStatusOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{4}
}
func (m *UpdatePaymentStatusOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePaymentStatusOutput.Unmarshal(m, b)
}
func (m *UpdatePaymentStatusOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePaymentStatusOutput.Marshal(b, m, deterministic)
}
func (dst *UpdatePaymentStatusOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePaymentStatusOutput.Merge(dst, src)
}
func (m *UpdatePaymentStatusOutput) XXX_Size() int {
	return xxx_messageInfo_UpdatePaymentStatusOutput.Size(m)
}
func (m *UpdatePaymentStatusOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePaymentStatusOutput.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePaymentStatusOutput proto.InternalMessageInfo

func (m *UpdatePaymentStatusOutput) GetResult() *Transaction {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetTransactionInput struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionInput) Reset()         { *m = GetTransactionInput{} }
func (m *GetTransactionInput) String() string { return proto.CompactTextString(m) }
func (*GetTransactionInput) ProtoMessage()    {}
func (*GetTransactionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{5}
}
func (m *GetTransactionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionInput.Unmarshal(m, b)
}
func (m *GetTransactionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionInput.Marshal(b, m, deterministic)
}
func (dst *GetTransactionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionInput.Merge(dst, src)
}
func (m *GetTransactionInput) XXX_Size() int {
	return xxx_messageInfo_GetTransactionInput.Size(m)
}
func (m *GetTransactionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionInput proto.InternalMessageInfo

func (m *GetTransactionInput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetTransactionOutput struct {
	Result               *Transaction `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTransactionOutput) Reset()         { *m = GetTransactionOutput{} }
func (m *GetTransactionOutput) String() string { return proto.CompactTextString(m) }
func (*GetTransactionOutput) ProtoMessage()    {}
func (*GetTransactionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{6}
}
func (m *GetTransactionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionOutput.Unmarshal(m, b)
}
func (m *GetTransactionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionOutput.Marshal(b, m, deterministic)
}
func (dst *GetTransactionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionOutput.Merge(dst, src)
}
func (m *GetTransactionOutput) XXX_Size() int {
	return xxx_messageInfo_GetTransactionOutput.Size(m)
}
func (m *GetTransactionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionOutput proto.InternalMessageInfo

func (m *GetTransactionOutput) GetResult() *Transaction {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetTransactionListInput struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionListInput) Reset()         { *m = GetTransactionListInput{} }
func (m *GetTransactionListInput) String() string { return proto.CompactTextString(m) }
func (*GetTransactionListInput) ProtoMessage()    {}
func (*GetTransactionListInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{7}
}
func (m *GetTransactionListInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionListInput.Unmarshal(m, b)
}
func (m *GetTransactionListInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionListInput.Marshal(b, m, deterministic)
}
func (dst *GetTransactionListInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionListInput.Merge(dst, src)
}
func (m *GetTransactionListInput) XXX_Size() int {
	return xxx_messageInfo_GetTransactionListInput.Size(m)
}
func (m *GetTransactionListInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionListInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionListInput proto.InternalMessageInfo

func (m *GetTransactionListInput) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTransactionListInput) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetTransactionListOutput struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTransactionListOutput) Reset()         { *m = GetTransactionListOutput{} }
func (m *GetTransactionListOutput) String() string { return proto.CompactTextString(m) }
func (*GetTransactionListOutput) ProtoMessage()    {}
func (*GetTransactionListOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{8}
}
func (m *GetTransactionListOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionListOutput.Unmarshal(m, b)
}
func (m *GetTransactionListOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionListOutput.Marshal(b, m, deterministic)
}
func (dst *GetTransactionListOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionListOutput.Merge(dst, src)
}
func (m *GetTransactionListOutput) XXX_Size() int {
	return xxx_messageInfo_GetTransactionListOutput.Size(m)
}
func (m *GetTransactionListOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionListOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionListOutput proto.InternalMessageInfo

func (m *GetTransactionListOutput) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type ConfirmPaymentCashInInput struct {
	PaymentID            string   `protobuf:"bytes,1,opt,name=PaymentID,proto3" json:"PaymentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPaymentCashInInput) Reset()         { *m = ConfirmPaymentCashInInput{} }
func (m *ConfirmPaymentCashInInput) String() string { return proto.CompactTextString(m) }
func (*ConfirmPaymentCashInInput) ProtoMessage()    {}
func (*ConfirmPaymentCashInInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{9}
}
func (m *ConfirmPaymentCashInInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPaymentCashInInput.Unmarshal(m, b)
}
func (m *ConfirmPaymentCashInInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPaymentCashInInput.Marshal(b, m, deterministic)
}
func (dst *ConfirmPaymentCashInInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPaymentCashInInput.Merge(dst, src)
}
func (m *ConfirmPaymentCashInInput) XXX_Size() int {
	return xxx_messageInfo_ConfirmPaymentCashInInput.Size(m)
}
func (m *ConfirmPaymentCashInInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPaymentCashInInput.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPaymentCashInInput proto.InternalMessageInfo

func (m *ConfirmPaymentCashInInput) GetPaymentID() string {
	if m != nil {
		return m.PaymentID
	}
	return ""
}

type ConfirmPaymentCashInOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPaymentCashInOutput) Reset()         { *m = ConfirmPaymentCashInOutput{} }
func (m *ConfirmPaymentCashInOutput) String() string { return proto.CompactTextString(m) }
func (*ConfirmPaymentCashInOutput) ProtoMessage()    {}
func (*ConfirmPaymentCashInOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_1d18d9899cddaf3f, []int{10}
}
func (m *ConfirmPaymentCashInOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPaymentCashInOutput.Unmarshal(m, b)
}
func (m *ConfirmPaymentCashInOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPaymentCashInOutput.Marshal(b, m, deterministic)
}
func (dst *ConfirmPaymentCashInOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPaymentCashInOutput.Merge(dst, src)
}
func (m *ConfirmPaymentCashInOutput) XXX_Size() int {
	return xxx_messageInfo_ConfirmPaymentCashInOutput.Size(m)
}
func (m *ConfirmPaymentCashInOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPaymentCashInOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPaymentCashInOutput proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PaymentAgent)(nil), "agent.PaymentAgent")
	proto.RegisterType((*History)(nil), "agent.History")
	proto.RegisterType((*Transaction)(nil), "agent.Transaction")
	proto.RegisterType((*UpdatePaymentStatusInput)(nil), "agent.UpdatePaymentStatusInput")
	proto.RegisterType((*UpdatePaymentStatusOutput)(nil), "agent.UpdatePaymentStatusOutput")
	proto.RegisterType((*GetTransactionInput)(nil), "agent.GetTransactionInput")
	proto.RegisterType((*GetTransactionOutput)(nil), "agent.GetTransactionOutput")
	proto.RegisterType((*GetTransactionListInput)(nil), "agent.GetTransactionListInput")
	proto.RegisterType((*GetTransactionListOutput)(nil), "agent.GetTransactionListOutput")
	proto.RegisterType((*ConfirmPaymentCashInInput)(nil), "agent.ConfirmPaymentCashInInput")
	proto.RegisterType((*ConfirmPaymentCashInOutput)(nil), "agent.ConfirmPaymentCashInOutput")
	proto.RegisterEnum("agent.PaymentStatus", PaymentStatus_name, PaymentStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentClient interface {
	ConfirmPaymentCashIn(ctx context.Context, in *ConfirmPaymentCashInInput, opts ...grpc.CallOption) (*ConfirmPaymentCashInOutput, error)
	GetTransactionList(ctx context.Context, in *GetTransactionListInput, opts ...grpc.CallOption) (*GetTransactionListOutput, error)
	GetTransaction(ctx context.Context, in *GetTransactionInput, opts ...grpc.CallOption) (*GetTransactionOutput, error)
	UpdatePaymentStatus(ctx context.Context, in *UpdatePaymentStatusInput, opts ...grpc.CallOption) (*UpdatePaymentStatusOutput, error)
}

type paymentClient struct {
	cc *grpc.ClientConn
}

func NewPaymentClient(cc *grpc.ClientConn) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) ConfirmPaymentCashIn(ctx context.Context, in *ConfirmPaymentCashInInput, opts ...grpc.CallOption) (*ConfirmPaymentCashInOutput, error) {
	out := new(ConfirmPaymentCashInOutput)
	err := c.cc.Invoke(ctx, "/agent.Payment/ConfirmPaymentCashIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetTransactionList(ctx context.Context, in *GetTransactionListInput, opts ...grpc.CallOption) (*GetTransactionListOutput, error) {
	out := new(GetTransactionListOutput)
	err := c.cc.Invoke(ctx, "/agent.Payment/GetTransactionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetTransaction(ctx context.Context, in *GetTransactionInput, opts ...grpc.CallOption) (*GetTransactionOutput, error) {
	out := new(GetTransactionOutput)
	err := c.cc.Invoke(ctx, "/agent.Payment/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) UpdatePaymentStatus(ctx context.Context, in *UpdatePaymentStatusInput, opts ...grpc.CallOption) (*UpdatePaymentStatusOutput, error) {
	out := new(UpdatePaymentStatusOutput)
	err := c.cc.Invoke(ctx, "/agent.Payment/UpdatePaymentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
type PaymentServer interface {
	ConfirmPaymentCashIn(context.Context, *ConfirmPaymentCashInInput) (*ConfirmPaymentCashInOutput, error)
	GetTransactionList(context.Context, *GetTransactionListInput) (*GetTransactionListOutput, error)
	GetTransaction(context.Context, *GetTransactionInput) (*GetTransactionOutput, error)
	UpdatePaymentStatus(context.Context, *UpdatePaymentStatusInput) (*UpdatePaymentStatusOutput, error)
}

func RegisterPaymentServer(s *grpc.Server, srv PaymentServer) {
	s.RegisterService(&_Payment_serviceDesc, srv)
}

func _Payment_ConfirmPaymentCashIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentCashInInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ConfirmPaymentCashIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Payment/ConfirmPaymentCashIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ConfirmPaymentCashIn(ctx, req.(*ConfirmPaymentCashInInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetTransactionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetTransactionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Payment/GetTransactionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetTransactionList(ctx, req.(*GetTransactionListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Payment/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetTransaction(ctx, req.(*GetTransactionInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_UpdatePaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentStatusInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).UpdatePaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Payment/UpdatePaymentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).UpdatePaymentStatus(ctx, req.(*UpdatePaymentStatusInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Payment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmPaymentCashIn",
			Handler:    _Payment_ConfirmPaymentCashIn_Handler,
		},
		{
			MethodName: "GetTransactionList",
			Handler:    _Payment_GetTransactionList_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _Payment_GetTransaction_Handler,
		},
		{
			MethodName: "UpdatePaymentStatus",
			Handler:    _Payment_UpdatePaymentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/payment.proto",
}

func init() {
	proto.RegisterFile("pkg/api/proto/payment.proto", fileDescriptor_payment_1d18d9899cddaf3f)
}

var fileDescriptor_payment_1d18d9899cddaf3f = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4b, 0x6f, 0x9b, 0x4c,
	0x14, 0xfd, 0x8c, 0x83, 0xfd, 0xe5, 0x3a, 0x75, 0xd0, 0xd8, 0x6d, 0x08, 0x89, 0x52, 0x17, 0xa9,
	0x92, 0x15, 0x55, 0xb1, 0x44, 0xd5, 0x4a, 0x5d, 0x74, 0x41, 0xb0, 0xe3, 0xa0, 0xfa, 0x25, 0x8c,
	0xa5, 0x3e, 0x16, 0x88, 0x26, 0xe3, 0x14, 0xd5, 0x06, 0x04, 0x43, 0x25, 0xef, 0xbb, 0xee, 0x8f,
	0xec, 0x2f, 0xa9, 0x98, 0x99, 0x38, 0x26, 0x40, 0x17, 0x5d, 0x79, 0xce, 0x7d, 0x9c, 0x7b, 0xe6,
	0x5c, 0xc6, 0x70, 0x12, 0x7e, 0xbf, 0xeb, 0xb9, 0xa1, 0xd7, 0x0b, 0xa3, 0x80, 0x04, 0xbd, 0xd0,
	0xdd, 0xac, 0xb1, 0x4f, 0x2e, 0x28, 0x42, 0xa2, 0x7b, 0x87, 0x7d, 0xa2, 0x6a, 0x70, 0x30, 0x63,
	0x71, 0x3d, 0xc5, 0xa8, 0x09, 0x82, 0xd9, 0x97, 0x2b, 0x9d, 0x4a, 0x77, 0xdf, 0x12, 0xcc, 0x3e,
	0x42, 0xb0, 0x67, 0x6f, 0x42, 0x2c, 0x0b, 0x34, 0x42, 0xcf, 0xea, 0x1b, 0xa8, 0x5f, 0x7b, 0x31,
	0x09, 0xa2, 0x0d, 0x7a, 0x06, 0xb5, 0x39, 0x71, 0x49, 0x12, 0xf3, 0x16, 0x8e, 0xd2, 0xb6, 0x31,
	0x5e, 0x07, 0xf7, 0x6d, 0xe9, 0x59, 0xfd, 0x29, 0x40, 0xc3, 0x8e, 0x5c, 0x3f, 0x76, 0x6f, 0x88,
	0x17, 0xf8, 0xb9, 0x51, 0xef, 0xe1, 0x90, 0x4b, 0x99, 0x45, 0xc1, 0x0f, 0xef, 0x16, 0x47, 0xb4,
	0xbd, 0xa1, 0xb5, 0x2e, 0xa8, 0xd6, 0x8b, 0x5d, 0xa1, 0xd6, 0xe3, 0x5a, 0xd4, 0x85, 0x43, 0xc3,
	0x8d, 0xbf, 0x99, 0xbe, 0x85, 0x97, 0x38, 0xc2, 0xfe, 0x0d, 0x96, 0xab, 0x94, 0xfb, 0x71, 0x18,
	0x29, 0xf0, 0xbf, 0x91, 0x44, 0xe9, 0x79, 0x23, 0xef, 0xd1, 0x92, 0x2d, 0x4e, 0x2f, 0xa4, 0xaf,
	0x83, 0xc4, 0x27, 0xb2, 0xd8, 0xa9, 0x74, 0x05, 0x8b, 0x23, 0xd4, 0xdd, 0xde, 0x59, 0xae, 0x75,
	0xaa, 0xdd, 0x86, 0xd6, 0xe4, 0xa2, 0x78, 0xd4, 0xda, 0x5a, 0x72, 0x06, 0xc0, 0x06, 0x52, 0xdf,
	0xea, 0x94, 0x7f, 0x27, 0xa2, 0xae, 0x40, 0x5e, 0x84, 0xb7, 0x2e, 0xc1, 0xfc, 0x02, 0xcc, 0x31,
	0xd3, 0x0f, 0x93, 0xbc, 0xfb, 0xaf, 0xb6, 0xf6, 0xa6, 0x4e, 0x34, 0xb5, 0x76, 0xd6, 0x09, 0x96,
	0xcb, 0x99, 0x5e, 0xdd, 0x31, 0x7d, 0x08, 0xc7, 0x05, 0xd3, 0xa6, 0x09, 0x49, 0xc7, 0x9d, 0x43,
	0x2d, 0xc2, 0x71, 0xb2, 0x22, 0x74, 0x64, 0x43, 0x43, 0x9c, 0x7e, 0x67, 0x4b, 0x16, 0xaf, 0x50,
	0x5f, 0x42, 0x6b, 0x88, 0xc9, 0x4e, 0xa6, 0x50, 0xb1, 0x7a, 0x09, 0xed, 0x6c, 0xd9, 0x3f, 0x8c,
	0x1a, 0xc2, 0x51, 0x96, 0x63, 0xe4, 0xc5, 0x84, 0x8d, 0x6b, 0x83, 0xb8, 0xf2, 0xd6, 0x1e, 0x63,
	0x11, 0x2d, 0x06, 0xd2, 0xa5, 0x05, 0xcb, 0x65, 0x8c, 0x09, 0xb5, 0x49, 0xb4, 0x38, 0x52, 0x2d,
	0x90, 0xf3, 0x44, 0x5c, 0xd0, 0x5b, 0x38, 0x20, 0x0f, 0x89, 0xf4, 0xfb, 0xad, 0x96, 0xc8, 0xca,
	0xd4, 0xa9, 0xef, 0xe0, 0xd8, 0x08, 0xfc, 0xa5, 0x17, 0xad, 0xb9, 0xa3, 0x6c, 0xb5, 0x4c, 0xde,
	0x29, 0xec, 0xf3, 0xe8, 0xd6, 0x94, 0x87, 0x80, 0x7a, 0x0a, 0x4a, 0x51, 0x2b, 0x13, 0x74, 0xfe,
	0xab, 0x02, 0x4f, 0x32, 0x4b, 0x42, 0x0d, 0xa8, 0x9b, 0x13, 0xd3, 0x36, 0xf5, 0x91, 0xf4, 0x1f,
	0x6a, 0x83, 0x64, 0x0d, 0xf4, 0xfe, 0x27, 0xc7, 0x9e, 0x3a, 0x86, 0x3e, 0xbf, 0x76, 0xcc, 0x89,
	0x54, 0x41, 0x2d, 0x38, 0xe4, 0xc0, 0x31, 0xa6, 0x93, 0x2b, 0xd3, 0x1a, 0x4b, 0x02, 0x3a, 0x05,
	0xd9, 0xd0, 0x47, 0xa3, 0x4b, 0xdd, 0xf8, 0xe0, 0xe8, 0xb6, 0x3d, 0x18, 0xcf, 0x6c, 0x67, 0xbe,
	0x30, 0x8c, 0xc1, 0x7c, 0x2e, 0x55, 0xd1, 0x09, 0x1c, 0xe5, 0xb2, 0x57, 0xba, 0x39, 0x1a, 0xf4,
	0xa5, 0x3d, 0x04, 0x50, 0xe3, 0x67, 0x51, 0xfb, 0x2d, 0x40, 0x9d, 0x0b, 0x42, 0x5f, 0xa0, 0x5d,
	0x24, 0x1d, 0x75, 0xb8, 0x5f, 0xa5, 0x96, 0x28, 0x2f, 0xfe, 0x52, 0xc1, 0x57, 0xb1, 0x00, 0x94,
	0x5f, 0x13, 0x3a, 0xe3, 0x8d, 0x25, 0x9f, 0x82, 0xf2, 0xbc, 0x34, 0xcf, 0x69, 0x4d, 0x68, 0x66,
	0x73, 0x48, 0x29, 0x6c, 0x61, 0x74, 0x27, 0x85, 0x39, 0x4e, 0xf5, 0x11, 0x5a, 0x05, 0xaf, 0x08,
	0xdd, 0x4b, 0x28, 0x7b, 0xcf, 0x4a, 0xa7, 0xbc, 0x80, 0x31, 0x5f, 0x1e, 0x7d, 0x7e, 0x1a, 0x07,
	0x4b, 0xe2, 0x63, 0xd2, 0xcb, 0xfc, 0x5b, 0x7f, 0xad, 0xd1, 0x9f, 0xd7, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x0f, 0x55, 0xd7, 0xee, 0xc5, 0x05, 0x00, 0x00,
}
